### PR TITLE
Add NE Scala 2020 schedule and confirmed talk details

### PR DESCRIPTION
**Pull request by stewSquared**

### CODE REVIEW

**Comment by ryan-williams** [comment]
- remove long/medium/lightning headers from RHS on confirmed talks page:
  image
  - can you make a heading for each one, and link to it from index.html?
- "Schedule is confirmed" links to ballot still
- include author names in index.html and talk details page
- I'd change "Be sure to check out the schedule for Typelevel Summit on Thursday, March 12!" to "we'll include the day 1 (Typelevel Summit) schedule here once it is announced", or equivalent.
  - Better yet, can't we just get it now/tonight? cc @LukaJCB

**Comment by stewSquared** [comment]
Headers on RHS already removed. I'll add anchors for the talks and change the text/link.

**Comment by LukaJCB** [comment]
TLS schedule: https://docs.google.com/spreadsheets/d/1QxnZ-CKjyGh6zZyu4muX6t4JyanNCEL4tCN5FyRzCUQ/edit?usp=sharing

**Comment by stewSquared** [comment]
I'll change the front page to a table, as in 2019

**Pull request merged**
