### PR TITLE
first draft of updated website

### PR DESCRIPTION
**Pull request by wheaties**
I've finally updated the website after many delays. Still having issues with Mastodon.

### CODE REVIEW

**Comment by JasnaMRB** [comment]
two small things: I'd make this text a little easier to read:
image

also I see this image overflow on my Linux Firefox: 
image

but not blockers for me, and can be in follow-up PRs if you want.

**Comment by JasnaMRB** [comment]
though I guess I can't approve anyway, so no blockers or approvals 😅

**Comment by wheaties** [comment]
That's wild! The image is 1900x735. I should probably add a max height to it, then.

**Comment by JasnaMRB** [comment]
The max height add looks good on my end now 🎉

**Pull request merged**
